Add pull-upstream workflow
jardon/deb-ci pull request #1
Opened 2023-06-01 15:45 UTC by jardon

inputs:
  - fork: Git repo fork to pull upstream and push updates required: true

secrets:
  - LP_USER: git user to configure 
  - LP_EMAIL: git email to configure

Github actions workflow for pulling upstream changes using gbp.

2023-06-05 20:20 UTC, jbicha requested changes

2023-06-05 20:20 UTC, jbicha commented on .github/workflows/gbp-pull-upstream.yaml
> +          dch -i "New upstream release"
I don't think we need to add a debian/changelog entry here.

2023-06-05 20:20 UTC, jbicha commented on .github/workflows/gbp-pull-upstream.yaml
> +          git commit -m "Update changelog and rebase patches"
It's possible that patches don't need to be rebased or anything added to the changelog. In that case, the command will complete but it won't return a 0 exit code. Maybe something like this is ok??

```sh
git commit -m "Rebase patches" || true
gbp dch
git add debian
git commit -m "Update changelog" || true
```

`gbp dch` updates debian/changelog with git commits since the last time debian/changelog was edited.

2023-06-06 17:21 UTC, jardon commented
I do need to merge some changes for SSH support as well for pushing the changes

2023-06-08 14:39 UTC, merged