Add gbp-build workflow
jardon/deb-ci pull request #3
Opened 2023-06-01 15:50 UTC by jardon

inputs:
  - branch: git branch to build
  - series: build series

secrets:
  - LP_USER: username used for lp account
  - LP_EMAIL: email used for lp account
  - GPG_PUB_KEY: gpg public key used for signing
  - GPG_PRIVATE_KEY: gpg private key used for signing

Build a project using gbp.  The workflow uploads the artifact on a successful run for use with other workflows.

2023-06-05 20:12 UTC, jbicha requested changes

2023-06-05 20:12 UTC, jbicha commented on config/.sbuildrc
> +$purge_build_directory = 'successful';
The CI workers don't need to purge anything. This line is useful for reducing hard drive space on user machines. Depending on your purpose for this file, you could comment out this line or remove it.

2023-06-05 20:12 UTC, jbicha commented on .github/workflows/gbp-build.yaml
> +        default: jammy
I guess our default should be lunar here. Many of the newest packages wouldn't build on jammy.

Same for the place a few lines down that also uses jammy

2023-06-06 10:52 UTC, seb128 commented on .github/workflows/gbp-build.yaml
> +          git clone ${{ github.event.inputs.repo }} project
using 'gbp clone' it should checkout pristine-tar and upstream branches automatically

2023-06-06 10:52 UTC, seb128 commented on .github/workflows/gbp-build.yaml
> +          sudo sbuild-launchpad-chroot create -n ${{ github.event.inputs.series }} -s ${{ github.event.inputs.series }} -a amd64
I wonder if we really need to recreate a sbuild env every time. How far is the stock container we get from a base system, maybe it's minimal enough that we could just build directly in the container? 

If not maybe sbuild is ok for now but perhaps we should investigate having a custom docker image instead of rebulding the env from scratch every time which seems a waste of resources

2023-06-06 10:54 UTC, seb128 commented on .github/workflows/gbp-build.yaml
> +          mkdir tarballs
is that one needed by gbp? if so it should also be able to create it no?

2023-06-06 10:56 UTC, seb128 commented on config/.devscripts
> +UBUMAIL=<email>
you shouldn't need the UBUMAIL if you already set DEBEMAIL?

2023-06-06 17:35 UTC, jardon commented on .github/workflows/gbp-build.yaml
> +        default: jammy
The workflow is designed to be generic here.  So if you wanted to build an older package, you could by supplying the right series and branch/tag.  The default being LTS does likely mean that you will need to specify the latest codename every time, but that also seems like something to have to update every six months.

2023-06-06 17:38 UTC, jardon commented on .github/workflows/gbp-build.yaml
> +          git clone ${{ github.event.inputs.repo }} project
The available version of `git-buildpackage` for the runner does not support this functionality unfortunately.  It could be backported or uploaded to a ppa.

2023-06-06 18:35 UTC, jbicha commented on .github/workflows/gbp-build.yaml
> +          git clone ${{ github.event.inputs.repo }} project
I believe `gbp clone` works but the `--add-upstream-vcs` option is not available in the Jammy version.

2023-06-06 18:46 UTC, seb128 commented on .github/workflows/gbp-build.yaml
> +          sudo sbuild-launchpad-chroot create -n ${{ github.event.inputs.series }} -s ${{ github.event.inputs.series }} -a amd64
Thanks for explaining, that is indeed a valid reason. I didn't check how expensive setting up the sbuild env is but I expect that most of the updates will target the devel serie so maybe we can take a note to see if we could special case the devel and avoid doing the extra work there?

2023-06-06 18:48 UTC, seb128 commented on .github/workflows/gbp-build.yaml
> +          git clone ${{ github.event.inputs.repo }} project
Which version of git-buildpackage is available there? It is a surprising statement because afaik 'gbp clone' has been setting up the pristine-tar and upstream checkouts for us for as long as we have been using git for pkg-gnome, maybe you are confusing with adding the upstream remote as Jeremy suggested?

2023-06-08 13:39 UTC, merged

2023-06-15 14:57 UTC, 3v1n0 commented on .github/workflows/gbp-build.yaml
> +          sudo -H -u runner bash -c "cd project;  gbp buildpackage --git-builder='debuild -S -nc'"
`runuser -u runner` is enough?

Also better to use `&&`